name: Automated API tests using Newman

on:
  push:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Newman and Htmlextra Reporter
        run: npm install -g newman newman-reporter-htmlextra
      - name: Run Newman with Htmlextra Reporter
        run: |
          newman run "full-stack-qa.postman_collection.json" \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export report.html
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: report.html
