name: Automated API tests using Postman CLI

on: push

jobs:
  postman-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "40791490-6a8b55c7-a20b-46f6-8a74-8164d7fb82c2" --env-var "token=${{ secrets.TOKEN }}"
